# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-25 04:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleadores',
            fields=[
                ('Nombre', models.CharField(max_length=50)),
                ('FechaConst', models.DateField()),
                ('RNC', models.IntegerField(primary_key=True, serialize=False)),
                ('Email', models.EmailField(max_length=50)),
                ('Clave', models.CharField(max_length=75)),
                ('Clave2', models.CharField(max_length=75)),
                ('Estado', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('Cod_Gen', models.AutoField(primary_key=True, serialize=False)),
                ('Descripcion', models.CharField(max_length=20)),
                ('Sigla', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Provincias',
            fields=[
                ('Cod_Provincia', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Solicitante',
            fields=[
                ('Cedula', models.IntegerField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=50)),
                ('Apellido', models.CharField(max_length=100)),
                ('Fecha_Nacimiento', models.DateField()),
                ('Email', models.EmailField(max_length=50)),
                ('Clave', models.CharField(max_length=75)),
                ('Clave2', models.CharField(max_length=75)),
                ('Estado', models.CharField(max_length=1)),
                ('Sexo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login_SignUp.Genero')),
            ],
        ),
        migrations.CreateModel(
            name='TipoEmpresa',
            fields=[
                ('Cod_TipoEmpr', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=10)),
                ('Descripcion', models.CharField(max_length=60)),
            ],
        ),
        migrations.AddField(
            model_name='empleadores',
            name='Direccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login_SignUp.Provincias'),
        ),
        migrations.AddField(
            model_name='empleadores',
            name='FormaJurd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login_SignUp.TipoEmpresa'),
        ),
    ]
